import { getSneakers } from '@/lib/sneakers';
import { Metadata } from 'next';

import SneakerCard from '@/components/SneakerCard';
import SneakerClientList from './SneakerClientList';

export const metadata: Metadata = {
  title: 'Sneaker page',
  description: 'Generated by create next app',
};
export default async function SneakerPage() {
  const sneakers = await getSneakers();
  return (
    <>
      <section
        style={{ backgroundPositionY: '80%' }}
        className="h-[300px] bg-[url('/sneaker/freepik__comic-art-graphic-novel-art-comic-illustration-hig__21363.jpeg')]  bg-cover  flex items-center justify-center"
      >
        <h1 className="p-[20px] h-[80px] bg-black text-white text-4xl font-bold drop-shadow-lg text-center">
          Lanzamiento
        </h1>
      </section>
      <section>
        <h1 className="text-2xl font-bold mb-4">Sneakers (Server Side)</h1>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {sneakers.map((s) => (
            <div key={s.id}>
              {/* Server rendered */}
              <div className="text-gray-500 text-xs mb-1">Renderizado en el servidor</div>
              <SneakerCard sneaker={s} />
            </div>
          ))}
        </div>
      </section>
      <SneakerClientList />
    </>
  );
}
